<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import api from '../api/client'
const router = useRouter()
const original = ref([]), drafts = ref([]), trainingNames = ref([]), deletedIds = ref([]), loading = ref(true), saving = ref(false), error = ref(''), success = ref('')
const blank = () => ({ id: null, title: '', maxScore: 100, batch: '', trainingName: '', repoUrl: '', dueDate: '' })
function optionsFor(value) { return value && !trainingNames.value.includes(value) ? [value, ...trainingNames.value] : trainingNames.value }
async function load() { loading.value = true; try { const [a, t] = await Promise.all([api.get('/assignments'), api.get('/interns/trainings/names')]); original.value = a.data; trainingNames.value = t.data; drafts.value = a.data.map(x => ({ id:x.id,title:x.title,maxScore:x.maxScore,batch:x.batch||'',trainingName:x.trainingName||'',repoUrl:x.repoUrl||'',dueDate:x.dueDate||'' })); deletedIds.value=[] } catch { error.value='Could not load assignments.' } finally { loading.value=false } }
function add() { drafts.value.push(blank()) }
function remove(index) { const row=drafts.value[index]; if (row.id && !window.confirm(`Mark "${row.title}" for deletion? Its grades will be removed when you save.`)) return; if (row.id) deletedIds.value.push(row.id); drafts.value.splice(index,1) }
function valid(row) { return row.title.trim() && Number.isFinite(Number(row.maxScore)) && Number(row.maxScore)>=0 }
const pendingCount = computed(() => { const source=new Map(original.value.map(x=>[x.id,JSON.stringify({title:x.title,maxScore:x.maxScore,batch:x.batch||'',trainingName:x.trainingName||'',repoUrl:x.repoUrl||'',dueDate:x.dueDate||''})])); return deletedIds.value.length+drafts.value.filter(x=>!x.id||source.get(x.id)!==JSON.stringify({title:x.title,maxScore:x.maxScore,batch:x.batch||'',trainingName:x.trainingName||'',repoUrl:x.repoUrl||'',dueDate:x.dueDate||''})).length })
async function saveAll() { error.value=''; success.value=''; if(drafts.value.some(x=>!valid(x))) { error.value='Every assignment needs a title and a non-negative maximum score.'; return } saving.value=true; try { await Promise.all(deletedIds.value.map(id=>api.delete(`/assignments/${id}`))); await Promise.all(drafts.value.map(x=>{const payload={...x,title:x.title.trim(),trainingName:x.trainingName||null,repoUrl:x.repoUrl||null,dueDate:x.dueDate||null};return x.id?api.put(`/assignments/${x.id}`,payload):api.post('/assignments',payload)})); success.value='All assignment changes were saved.'; await load() } catch { error.value='Some changes could not be saved. Review the assignments and try again.' } finally { saving.value=false } }
onMounted(load)
</script>
<template><div class="page"><div class="page-header head"><div><router-link to="/assignments" class="back">← Assignments and Grades</router-link><h1>Manage Assignments</h1><p class="subtitle">Make all additions, edits, and deletions here, then save them together.</p></div><div class="actions"><button class="btn btn--secondary" @click="add">Add assignment</button><button class="btn btn--primary" :disabled="saving||pendingCount===0" @click="saveAll">{{ saving?'Saving…':`Save Changes${pendingCount?` (${pendingCount})`:''}` }}</button></div></div><p v-if="error" class="error section">{{error}}</p><p v-if="success" class="success section">{{success}}</p><p v-if="loading" class="muted">Loading assignments…</p><section v-else class="card section"><p v-if="!drafts.length" class="muted">No assignments yet. Select “Add assignment” to create one.</p><div v-for="(row,index) in drafts" :key="row.id||`new-${index}`" class="editor"><div class="field"><label>Title</label><input class="input" v-model="row.title" /></div><div class="field"><label>Training</label><select class="select" v-model="row.trainingName"><option value="">Independent assignment</option><option v-for="name in optionsFor(row.trainingName)" :key="name" :value="name">{{name}}</option></select></div><div class="field small"><label>Max score</label><input class="input" v-model.number="row.maxScore" type="number" min="0" /></div><div class="field"><label>Batch</label><input class="input" v-model="row.batch" /></div><div class="field"><label>Due date</label><input class="input" v-model="row.dueDate" type="date" /></div><div class="field"><label>Box Drive link</label><input class="input" v-model="row.repoUrl" /></div><button class="btn btn--danger" @click="remove(index)">Delete</button></div></section></div></template>
<style scoped>.head,.actions{display:flex;justify-content:space-between;align-items:flex-start;gap:var(--sp-03);flex-wrap:wrap}.back{display:inline-block;margin-bottom:var(--sp-02)}.editor{display:grid;grid-template-columns:1.3fr 1fr 110px 1fr 150px 1.3fr auto;gap:var(--sp-02);align-items:end;padding:var(--sp-03) 0;border-bottom:1px solid var(--border)}.success{color:var(--support-success,#198038);font-weight:600}@media(max-width:1100px){.editor{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.editor{grid-template-columns:1fr}}</style>
