<script setup>
import { computed, onMounted, ref } from 'vue'
import api from '../api/client'
import auth from '../services/auth'
const assignments=ref([]), interns=ref([]), grades=ref([]), error=ref('')
const filterBatch=ref(''), filterAssignment=ref(''), filterDate=ref('')
const batches=computed(()=>[...new Set(interns.value.map(i=>i.batch).filter(Boolean))].sort())
const dates=computed(()=>[...new Set(assignments.value.map(a=>a.dueDate).filter(Boolean))].sort())
const shownAssignments=computed(()=>assignments.value.filter(a=>(!filterAssignment.value||a.id===Number(filterAssignment.value))&&(!filterDate.value||a.dueDate===filterDate.value)))
const shownInterns=computed(()=>interns.value.filter(i=>!filterBatch.value||i.batch===filterBatch.value))
const gradeMap=computed(()=>Object.fromEntries(grades.value.map(g=>[`${g.internId}-${g.assignmentId}`,g.score])))
function score(internId,assignmentId){const value=gradeMap.value[`${internId}-${assignmentId}`];return value==null?'—':value}
function clear(){filterBatch.value='';filterAssignment.value='';filterDate.value=''}
async function load(){try{const [a,i,g]=await Promise.all([api.get('/assignments'),api.get('/interns'),api.get('/submissions')]);assignments.value=a.data;interns.value=i.data;grades.value=g.data}catch{error.value='Could not load assignments and grades.'}}
onMounted(load)
</script>
<template><div class="page"><div class="page-header head"><div><h1>Assignments and Grades</h1><p class="subtitle">Every intern's score per assignment. Select an intern to record or change a grade.</p></div><router-link v-if="auth.isAdmin.value" to="/assignments/manage" class="btn btn--primary">Manage assignments</router-link></div><p v-if="error" class="error section">{{error}}</p><section class="card section filters"><div class="field"><label>Batch</label><select class="select" v-model="filterBatch"><option value="">All batches</option><option v-for="batch in batches" :key="batch">{{batch}}</option></select></div><div class="field"><label>Assignment</label><select class="select" v-model="filterAssignment"><option value="">All assignments</option><option v-for="a in assignments" :key="a.id" :value="a.id">{{a.title}}</option></select></div><div class="field"><label>Due date</label><select class="select" v-model="filterDate"><option value="">All dates</option><option v-for="date in dates" :key="date">{{date}}</option></select></div><button class="btn btn--ghost" @click="clear">Clear</button></section><div class="table-wrap"><table class="data-table"><thead><tr><th>Intern</th><th v-for="a in shownAssignments" :key="a.id"><div class="assignment-head"><strong>{{a.title}}</strong><span v-if="a.trainingName" class="muted">{{a.trainingName}}</span><span class="muted">max {{a.maxScore}}</span><span v-if="a.dueDate" class="muted">due {{a.dueDate}}</span></div></th></tr></thead><tbody><tr v-if="!shownInterns.length"><td :colspan="shownAssignments.length+1" class="muted">No interns match the current filters.</td></tr><tr v-for="intern in shownInterns" :key="intern.id"><td><router-link :to="`/interns/${intern.id}/progress`">{{intern.name}}</router-link></td><td v-for="a in shownAssignments" :key="a.id" class="score">{{score(intern.id,a.id)}}</td></tr></tbody></table></div></div></template>
<style scoped>.head,.filters{display:flex;align-items:flex-end;justify-content:space-between;gap:var(--sp-03);flex-wrap:wrap}.filters .field{min-width:180px;flex:1}.assignment-head{display:flex;flex-direction:column;gap:2px;align-items:center}.assignment-head .muted{font-size:12px;font-weight:400}.score{text-align:center}</style>
