<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { jsPDF } from 'jspdf'
import api from '../api/client'
const route=useRoute(),intern=ref(null),progress=ref(null),attendance=ref(null),grades=ref(null),trainings=ref([]),error=ref('')
async function load(){try{const id=route.params.id;const [i,p,a,g,t]=await Promise.all([api.get(`/interns/${id}`),api.get(`/interns/${id}/progress`),api.get(`/attendance/summary?internId=${id}`),api.get(`/interns/${id}/grades`),api.get(`/interns/${id}/trainings`)]);intern.value=i.data;progress.value=p.data;attendance.value=a.data;grades.value=g.data;trainings.value=t.data}catch{error.value='Could not prepare this intern summary for printing.'}}
function downloadPdf(){
  if(!intern.value) return
  const pdf=new jsPDF({unit:'pt',format:'a4'}), left=48, width=499
  let y=55
  const line=(text,size=10,bold=false)=>{pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(size);const lines=pdf.splitTextToSize(String(text),width);if(y+lines.length*(size+4)>790){pdf.addPage();y=55}pdf.text(lines,left,y);y+=lines.length*(size+4)+6}
  const heading=(text)=>{y+=10;line(text,15,true);pdf.setDrawColor(220);pdf.line(left,y,left+width,y);y+=10}
  pdf.setFillColor(15,98,254);pdf.rect(0,0,595,10,'F')
  line(intern.value.name,24,true);line(`${intern.value.track||'Intern'}${intern.value.batch?` · ${intern.value.batch}`:''}`,11);line(`Status: ${(intern.value.status||'ACTIVE').replaceAll('_',' ')}`,10,true)
  heading('Internship Profile')
  line(`Talent ID: ${intern.value.talentId||'Not recorded'}`);line(`School: ${intern.value.school||'Not recorded'}`);line(`Course: ${intern.value.course||'Not recorded'}`);line(`Expected graduation: ${intern.value.expectedGraduationDate||'Not recorded'}`);line(`Expected internship end: ${intern.value.expectedInternshipEndDate||'Not recorded'}`);line(`Required hours: ${intern.value.totalHoursRequired??'Not recorded'}`)
  if(progress.value){heading('Progress Overview');line(`Assignments completed: ${progress.value.completedAssignments} / ${progress.value.totalAssignments}`);line(`Completion rate: ${progress.value.completionPercentage}%`);line(`Average score: ${progress.value.averageScorePercentage}%`);line(`Attendance rate: ${attendance.value?.attendancePercentage??'—'}%`)}
  if(grades.value){heading('Training and Assessment Results');for(const category of grades.value.categories||[]){line(`${category.trainingName}: ${category.totalScore??'—'} / ${category.totalMaxScore??'—'}${category.totalPercentage!=null?` (${category.totalPercentage}%)`:''}`,11,true);for(const item of category.assignments)line(`• ${item.title}: ${item.score==null?'Not graded':`${item.score} / ${item.maxScore}`}`)}if(grades.value.independentAssignments?.length){line('Independent Assignments',11,true);for(const item of grades.value.independentAssignments)line(`• ${item.title}: ${item.score==null?'Not graded':`${item.score} / ${item.maxScore}`}`)}}
  heading('Completed Training');if(trainings.value.length)trainings.value.forEach(t=>line(`• ${t.trainingName}`));else line('No training recorded.')
  y+=12;line(`Learning Progress Dashboard · Generated ${new Date().toLocaleDateString()}`,8)
  pdf.save(`${intern.value.name.replace(/[^a-z0-9]+/gi,'-').replace(/(^-|-$)/g,'')||'intern'}-profile.pdf`)
}
onMounted(load)
</script>
<template><main class="print-page"><div class="actions"><router-link :to="`/interns/${route.params.id}/progress`" class="btn btn--secondary">Back to profile</router-link><button class="btn btn--primary" @click="downloadPdf">Download PDF</button></div><p v-if="error" class="error">{{error}}</p><article v-else-if="intern" class="resume"><header><div><h1>{{intern.name}}</h1><p>{{intern.track||'Intern'}}<template v-if="intern.batch"> · {{intern.batch}}</template></p></div><strong class="status">{{(intern.status||'ACTIVE').replaceAll('_',' ')}}</strong></header><section><h2>Internship Profile</h2><dl class="details"><div><dt>Talent ID</dt><dd>{{intern.talentId||'Not recorded'}}</dd></div><div><dt>School</dt><dd>{{intern.school||'Not recorded'}}</dd></div><div><dt>Course</dt><dd>{{intern.course||'Not recorded'}}</dd></div><div><dt>Expected graduation</dt><dd>{{intern.expectedGraduationDate||'Not recorded'}}</dd></div><div><dt>Expected internship end</dt><dd>{{intern.expectedInternshipEndDate||'Not recorded'}}</dd></div><div><dt>Required hours</dt><dd>{{intern.totalHoursRequired??'Not recorded'}}</dd></div></dl></section><section v-if="progress"><h2>Progress Overview</h2><div class="metrics"><div><strong>{{progress.completedAssignments}} / {{progress.totalAssignments}}</strong><span>Assignments completed</span></div><div><strong>{{progress.completionPercentage}}%</strong><span>Completion rate</span></div><div><strong>{{progress.averageScorePercentage}}%</strong><span>Average score</span></div><div><strong>{{attendance?.attendancePercentage??'—'}}%</strong><span>Attendance rate</span></div></div></section><section v-if="grades"><h2>Training and Assessment Results</h2><div v-for="category in grades.categories" :key="category.trainingName" class="grade"><div><h3>{{category.trainingName}}</h3><strong>{{category.totalScore??'—'}} / {{category.totalMaxScore??'—'}}<template v-if="category.totalPercentage!=null"> · {{category.totalPercentage}}%</template></strong></div><p v-for="item in category.assignments" :key="item.assignmentId">{{item.title}} <span>{{item.score==null?'Not graded':`${item.score} / ${item.maxScore}`}}</span></p></div><div v-if="grades.independentAssignments?.length" class="grade"><h3>Independent Assignments</h3><p v-for="item in grades.independentAssignments" :key="item.assignmentId">{{item.title}} <span>{{item.score==null?'Not graded':`${item.score} / ${item.maxScore}`}}</span></p></div></section><section><h2>Completed Training</h2><ul><li v-for="training in trainings" :key="training.id">{{training.trainingName}}</li></ul></section><footer>Learning Progress Dashboard · Generated {{new Date().toLocaleDateString()}}</footer></article></main></template>
<style scoped>.print-page{max-width:900px;margin:auto;padding:32px;background:#fff}.actions{display:flex;justify-content:flex-end;gap:12px;margin-bottom:24px}.resume{border-top:8px solid #0f62fe;padding:32px}.resume header,.grade>div{display:flex;justify-content:space-between;gap:24px;align-items:flex-start}.resume h1{font-size:38px}.resume h2{font-size:20px;margin:30px 0 14px;padding-bottom:7px;border-bottom:1px solid #dde1e6}.resume h3{font-size:16px}.status{text-transform:capitalize;background:#edf5ff;color:#0353e9;padding:6px 10px}.details,.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.details dt,.metrics span{color:#525252;font-size:13px}.details dd{margin:3px 0 0;font-weight:600}.metrics div{border-left:3px solid #0f62fe;padding-left:10px}.metrics strong,.metrics span{display:block}.grade{padding:12px 0;border-bottom:1px solid #dde1e6}.grade p{display:flex;justify-content:space-between;margin:7px 0}footer{margin-top:40px;color:#525252;font-size:12px;border-top:1px solid #dde1e6;padding-top:14px}@media(max-width:650px){.details,.metrics{grid-template-columns:repeat(2,1fr)}}@media print{.actions{display:none}.print-page{padding:0}.resume{border-top-width:5px}}</style>
