<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import api from '../api/client'
const route=useRoute(),intern=ref(null),progress=ref(null),attendance=ref(null),grades=ref(null),trainings=ref([]),error=ref('')
async function load(){try{const id=route.params.id;const [i,p,a,g,t]=await Promise.all([api.get(`/interns/${id}`),api.get(`/interns/${id}/progress`),api.get(`/attendance/summary?internId=${id}`),api.get(`/interns/${id}/grades`),api.get(`/interns/${id}/trainings`)]);intern.value=i.data;progress.value=p.data;attendance.value=a.data;grades.value=g.data;trainings.value=t.data}catch{error.value='Could not prepare this intern summary for printing.'}}
onMounted(load)
</script>
<template><main class="print-page"><div class="actions"><router-link :to="`/interns/${route.params.id}/progress`" class="btn btn--secondary">Back to profile</router-link><button class="btn btn--primary" @click="window.print()">Print</button></div><p v-if="error" class="error">{{error}}</p><article v-else-if="intern" class="resume"><header><div><h1>{{intern.name}}</h1><p>{{intern.track||'Intern'}}<template v-if="intern.batch"> · {{intern.batch}}</template></p></div><strong class="status">{{(intern.status||'ACTIVE').replaceAll('_',' ')}}</strong></header><section><h2>Internship Profile</h2><dl class="details"><div><dt>Talent ID</dt><dd>{{intern.talentId||'Not recorded'}}</dd></div><div><dt>School</dt><dd>{{intern.school||'Not recorded'}}</dd></div><div><dt>Course</dt><dd>{{intern.course||'Not recorded'}}</dd></div><div><dt>Expected graduation</dt><dd>{{intern.expectedGraduationDate||'Not recorded'}}</dd></div><div><dt>Expected internship end</dt><dd>{{intern.expectedInternshipEndDate||'Not recorded'}}</dd></div><div><dt>Required hours</dt><dd>{{intern.totalHoursRequired??'Not recorded'}}</dd></div></dl></section><section v-if="progress"><h2>Progress Overview</h2><div class="metrics"><div><strong>{{progress.completedAssignments}} / {{progress.totalAssignments}}</strong><span>Assignments completed</span></div><div><strong>{{progress.completionPercentage}}%</strong><span>Completion rate</span></div><div><strong>{{progress.averageScorePercentage}}%</strong><span>Average score</span></div><div><strong>{{attendance?.attendancePercentage??'—'}}%</strong><span>Attendance rate</span></div></div></section><section v-if="grades"><h2>Training and Assessment Results</h2><div v-for="category in grades.categories" :key="category.trainingName" class="grade"><div><h3>{{category.trainingName}}</h3><strong>{{category.totalScore??'—'}} / {{category.totalMaxScore??'—'}}<template v-if="category.totalPercentage!=null"> · {{category.totalPercentage}}%</template></strong></div><p v-for="item in category.assignments" :key="item.assignmentId">{{item.title}} <span>{{item.score==null?'Not graded':`${item.score} / ${item.maxScore}`}}</span></p></div><div v-if="grades.independentAssignments?.length" class="grade"><h3>Independent Assignments</h3><p v-for="item in grades.independentAssignments" :key="item.assignmentId">{{item.title}} <span>{{item.score==null?'Not graded':`${item.score} / ${item.maxScore}`}}</span></p></div></section><section><h2>Completed Training</h2><ul><li v-for="training in trainings" :key="training.id">{{training.trainingName}}</li></ul></section><footer>Learning Progress Dashboard · Generated {{new Date().toLocaleDateString()}}</footer></article></main></template>
<style scoped>.print-page{max-width:900px;margin:auto;padding:32px;background:#fff}.actions{display:flex;justify-content:flex-end;gap:12px;margin-bottom:24px}.resume{border-top:8px solid #0f62fe;padding:32px}.resume header,.grade>div{display:flex;justify-content:space-between;gap:24px;align-items:flex-start}.resume h1{font-size:38px}.resume h2{font-size:20px;margin:30px 0 14px;padding-bottom:7px;border-bottom:1px solid #dde1e6}.resume h3{font-size:16px}.status{text-transform:capitalize;background:#edf5ff;color:#0353e9;padding:6px 10px}.details,.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.details dt,.metrics span{color:#525252;font-size:13px}.details dd{margin:3px 0 0;font-weight:600}.metrics div{border-left:3px solid #0f62fe;padding-left:10px}.metrics strong,.metrics span{display:block}.grade{padding:12px 0;border-bottom:1px solid #dde1e6}.grade p{display:flex;justify-content:space-between;margin:7px 0}footer{margin-top:40px;color:#525252;font-size:12px;border-top:1px solid #dde1e6;padding-top:14px}@media(max-width:650px){.details,.metrics{grid-template-columns:repeat(2,1fr)}}@media print{.actions{display:none}.print-page{padding:0}.resume{border-top-width:5px}}</style>
